### ISSUE TITLE
Quicklisp install fails

### ISSUE THREAD

**Issue by rpx99** [ak-coram/cl-frugal-uuid#3]
Unfortunately the project doesn't load from quicklisp.

`cd ~/quicklisp/local-projects`
`git clone https://github.com/ak-coram/cl-frugal-uuid.git `

Sbcl:
`(ql:quickload "frugal-uuid")` works.

Remark: 
`(ql:quickload :frugal-uuid)` fails.

Think it should be consistently named as _**cl**-frugal-uuid_

Why only _frugal-uuid_ for quicklisp?

Thanks.

**Comment by ak-coram** [comment]
@rpx99 Thanks for reporting this issue. Both of your examples (`"frugal-uuid"` and `:frugal-uuid`) seem to work for me on multiple implementations (even when cloning the repository as `cl-frugal-uuid`). The CI workflow also relies on the keyword version: https://github.com/ak-coram/cl-frugal-uuid/blob/main/.github/workflows/CI.yml#L47

What OS are you using?

I usually prefix my Common Lisp repository names with `cl-`, but since Quicklisp & ASDF are about Common Lisp I don't see the point in including the `cl-` prefix in the system and package names. The directory name itself shouldn't matter anyway since ASDF scans these directories for `.asd` files recursively (and for example can even find systems named `:frugal-uuid/non-frugal/strong-random`, which cannot be mapped to a directory name directly).

The directory name can also be simply specified as an additional argument to git clone if you prefer: `git clone https://github.com/ak-coram/cl-frugal-uuid.git frugal-uuid`

I'm a bit reluctant renaming the systems & packages at this point for compatibility reasons.

**Comment by rpx99** [comment]
Thanks for your reply!

What I actually mean is that your project does not seem to be in quicklisp so that users can get it from the internet as a download. I did a _(ql:update-dist "quicklisp")_ to get the latest packages (_2023-21-10_). But _frugal-uuid_ does not seem to be available.

Cannot find an issue here (where you registered _frugal-uuid_): 
https://github.com/quicklisp/quicklisp-projects/issues?q=is%3Aissue+frugal

Maybe you did send it in by e-mail?  
http://blog.quicklisp.org/2015/01/getting-library-into-quicklisp.html

The missing download via quicklisp then brought me to the installation as a quicklisp local-project.

My observation installing using keyword :frugal-uuid turned out to be an issue with my Emacs. Sorry about that! (So no issue).

After all my hassle I was asking myself if the name was even correct I was using. So, is actually _frugal-uuid_ or maybe instead cl-frugal-uuid correct? I was confused:

**cl**-frugal-uuid can be installed via [Quicklisp](https://www.quicklisp.org/) 
but the actual quickload command says **:frugal-uuid**

In the back of my mind it causes a mismatch error :-)

Cheers.

**Comment by ak-coram** [comment]
I see, that clears it up :)

I didn't request the library to be added to the default Quicklisp dist, but it is available via the Ultralisp dist (which should automatically track the latest version on GitHub): https://ultralisp.org/

Here are the instructions for installing using Ultralisp:
https://github.com/ak-coram/cl-frugal-uuid?tab=readme-ov-file#installation

**Comment by kilianmh** [comment]
- For systems that are distributed via the default Quicklisp distribution, this library (and dependencies) have to also be in it.
- Will you open the [issue in Quicklisp Projects](https://github.com/quicklisp/quicklisp-projects/issues) that? Else I can also do it.
- The same has to be done for [trivial-clock](https://github.com/ak-coram/cl-trivial-clock), or we switch to [precise-time](https://github.com/Shinmera/precise-time), which appears to support mac and mezzano, and should be [in the next Quicklisp release](https://github.com/quicklisp/quicklisp-projects/issues/2422).
