### ISSUE TITLE
RFC compliance

### ISSUE THREAD

**Issue by kilianmh** [ak-coram/cl-frugal-uuid#4]
In May, [RFC 9562](https://www.rfc-editor.org/rfc/rfc9562) was finished.
Is this library compliant with the standard?

**Comment by ak-coram** [comment]
I've checked the changes since version 11 of the draft and didn't see anything that would affect this implementation. I've updated the README to refer to the final RFC.

Please keep in mind that the non-frugal system is probably much closer to the RFC (timestamp accuracy, randomness quality, etc.) when generating UUID values.

The library itself was originally based on RFC 4122, so the internal representation (slot names, etc.) doesn't reflect the contents of the new UUID versions at all. I'm not a heavy user of the new versions myself (I mostly rely on version 4) and I don't know of anyone making use of them via this library either, but as far as I can tell the implementation should be compliant. It's definitely a bug if it isn't.
